name: Build & Release Windows EXE

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # 1. Grab the source code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up the exact Python version your app targets
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install every runtime dependency that main.py imports (and sub‐deps like soundfile for librosa)
      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install \
            pyinstaller \
            pyside6 \
            pyqtgraph \
            librosa \
            soundfile \
            numpy \
            scipy \
            pyinstaller-hooks-contrib \
            matplotlib \

      # 4. Ensure the WinSparkle DLL is in the build context so PyInstaller can bundle it.
      - name: Ensure WinSparkle DLL
        shell: bash
        run: |
          if [ ! -f WinSparkle.dll ]; then
            cp tools/WinSparkle.dll ./WinSparkle.dll
          else
            echo "WinSparkle.dll already present, skipping copy."
          fi

      # 5. Build with enhanced options for single-file reliability
      - name: Build Windows EXE
        shell: bash
        run: |
          pyinstaller --noconfirm --noconsole --onefile main.py \
                      --name AudioSpectroDemo \
                      --add-data "WinSparkle.dll;." \
                      --exclude-module tkinter \
                      --exclude-module test \
                      --exclude-module unittest \
                      --strip \
                      --noupx \
                      --clean \
                      --hidden-import=PIL._tkinter_finder \
                      --hidden-import=scipy.special.cython_special \
                      --hidden-import=scipy._lib.messagestream \
                      --collect-all soundfile \
                      --collect-all librosa \
                      --collect-all scipy \
                      --collect-all ssl \
                      --collect-all certifi

      # 6. Stash the build output so you can download it from the workflow run if the release‐creation step fails.
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/AudioSpectroDemo.exe

      # 7. Create / update the GitHub Release tagged by the push.
      - name: Create GitHub Release
        id: make_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8. Attach the freshly‐built EXE to the release page.
      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.make_release.outputs.upload_url }}
          asset_path: dist/AudioSpectroDemo.exe
          asset_name: AudioSpectroDemo-${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}