name: Build & Release Windows EXE

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyside6 pyqtgraph librosa soundfile numpy pyinstaller-hooks-contrib

      - name: Download WinSparkle DLL
        shell: bash
        run: |
          curl -L -o winsparkle.dll \
            https://github.com/vslavik/winsparkle/releases/latest/download/WinSparkle.dll

      - name: Build Windows EXE
        shell: bash
        run: |
          pyinstaller --noconfirm --onefile main.py \
                      --name AudioSpectroDemo \
                      --add-data "winsparkle.dll;."

      - name: Create GitHub Release
        id: make_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.make_release.outputs.upload_url }}
          asset_path: dist/AudioSpectroDemo.exe
          asset_name: AudioSpectroDemo-${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
