name: Windows-PyInstaller

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyside6 pyqtgraph librosa soundfile numpy pyinstaller-hooks-contrib

    - name: Download WinSparkle DLL
      run: |
        curl -L -o winsparkle.dll https://github.com/vslavik/winsparkle/releases/latest/download/WinSparkle.dll

    - name: Freeze app
      run: |
        pyinstaller --noconfirm --onefile main.py --name AudioSpectroDemo --add-data "winsparkle.dll;."

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: AudioSpectroDemo.exe
        path: dist/AudioSpectroDemo.exe